REM INSERTING into G2990016
SET DEFINE OFF;
Insert into G2990016 (COD_CIA,TIP_LUGAR_SALTO,NUM_SECU,COD_EST,NOM_PRG,NOM_PRG_LLAMA_EST,COD_USR,FEC_ACTU) values ('1','G','2',null,'EM_P_CAMBIA_GESTOR_PAGADOR_MCR',null,'TRON2000',to_date('19/07/21','DD/MM/RR'));
commit;