CREATE TABLE "TRON2000"."A5021691_MCR" (
    "COD_CIA"             NUMBER(2, 0)
        NOT NULL ENABLE,
    "ID_PROCESO"          NUMBER
        NOT NULL ENABLE,
    "FEC_PROCESO"         DATE
        NOT NULL ENABLE,
    "CANTIDAD_REGISTROS"  NUMBER
        NOT NULL ENABLE,
    "COD_DOCUM"           VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "NOMBRE_TERCERO"      VARCHAR2(160 BYTE)
        NOT NULL ENABLE,
    "APE1_TERCERO"        VARCHAR2(80 BYTE),
    "APE2_TERCERO"        VARCHAR2(80 BYTE),
    "NUM_TARJETA"         VARCHAR2(30 BYTE)
        NOT NULL ENABLE,
    "MCA_PROCESADO"       VARCHAR2(1 BYTE),
    "NUM_AVISO"           VARCHAR2(20 BYTE),
    "OBSERVACIONES"       VARCHAR2(150 BYTE),
    "COD_USR"             VARCHAR2(20 BYTE)
        NOT NULL ENABLE,
    "FEC_ACTU"            DATE
        NOT NULL ENABLE,
    "NUM_RECIBO"          NUMBER,
    "NOMBRE_ARCHIVO"      VARCHAR2(50 BYTE),
    "NUM_POLIZA"          VARCHAR2(13 BYTE),
    "NUM_SPTO"            NUMBER,
    "TIP_DOCUM"           VARCHAR2(3 BYTE)
)
SEGMENT CREATION IMMEDIATE
PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
TABLESPACE "USERS";

COMMENT ON TABLE "TRON2000"."A5021691_MCR" IS
    'REGISTRO DE PROCESO RAMO 230 MASIVO DE NUM_AVISO';

CREATE INDEX "TRON2000"."IDX_FBE10001" ON
    "TRON2000"."A5021691_MCR" (
        "NUM_TARJETA",
        "COD_DOCUM"
    )
        PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
            STORAGE ( INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT )
        TABLESPACE "DATOS";

GRANT SELECT ON "TRON2000"."A5021691_MCR" TO "RSEL_TRON2000_ALIADOS";

GRANT DELETE ON "TRON2000"."A5021691_MCR" TO "NWT_DM_APP";

GRANT INSERT ON "TRON2000"."A5021691_MCR" TO "NWT_DM_APP";

GRANT SELECT ON "TRON2000"."A5021691_MCR" TO "NWT_DM_APP";

GRANT UPDATE ON "TRON2000"."A5021691_MCR" TO "NWT_DM_APP";